### ISSUE TITLE
checkbox fields

### ISSUE THREAD

**Issue by CarCarlo1977** [codeshell/fpdm#4]
Hi,
i have a strange issue on checkbox filled with FPDM, on mac preview there is no problem in showing but on adobe acrobat reader the checkboxes aren't showed.
Sometimes on other Mac OS i can see that on checkboxes are present 2 marks...

Maybe the issue is that the font that is used for check mark is ZapfDingbats, but in pdf template created with adobe acrobat pro, the default font used for is AdobePi.

Here : http://webprogramming.ninja/2015/12/28/fpdf-and-the-check-mark/
there is a solution for fpdf.

is there a way for using a different font/char in fpdm for check marks?

thanks for your great work! i hope we can found a useful solution for community!

Carlo

**Comment by codeshell** [comment]
How did you 'fill checkboxes with FPDM'? According to the original author of FPDM (and looking into the code base) it should not be possible to toggle checkboxes because it is not implemented. Just setting a value shouldn't work on a checkbox field because it has no text value.

That said I added parsing checkbox definitions to the code. Feel free to try it out. For now, it's on a separate branch:
https://github.com/codeshell/fpdm/tree/change-checkboxes

Set the value of a checkbox field with anything that evaluates to 'true' or 'false'. If there was a checkbox definition detected it will be transformed to a checkbox state.

**Comment by codeshell** [comment]
implemented in v2.9.2

can be activated with `$pdf->useCheckboxParser = true;`
